package store

import "go-api-structure/internal/store/db"

// SQLStore provides a concrete implementation of the Store interface using a *sql.DB connection pool.
// It holds a *db.Queries object, which is generated by sqlc.
// This struct will be the receiver for methods that implement UserStore, VendorStore, and MerchantStore.
type SQLStore struct {
	*db.Queries
	// db *sql.DB // The database connection pool, needed for transactions if not handled by sqlc's Querier directly.
	// For now, *db.Queries takes a db.DBTX, which can be *sql.DB or *sql.Tx.
}

// NewStore creates a new SQLStore.
func NewStore(dbTX db.DBTX) Store {
	return &SQLStore{
		Queries: db.New(dbTX),
		// db: // if we were managing transactions manually here
	}
}
