// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: vendors.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVendor = `-- name: CreateVendor :one
INSERT INTO vendors (
    user_id,
    name,
    description
) VALUES (
    $1, $2, $3
) RETURNING id, name, description, user_id, created_at, updated_at
`

type CreateVendorParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateVendor(ctx context.Context, arg CreateVendorParams) (Vendor, error) {
	row := q.db.QueryRow(ctx, createVendor, arg.UserID, arg.Name, arg.Description)
	var i Vendor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteVendor = `-- name: DeleteVendor :exec
DELETE FROM vendors
WHERE id = $1 AND user_id = $2
`

type DeleteVendorParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteVendor(ctx context.Context, arg DeleteVendorParams) error {
	_, err := q.db.Exec(ctx, deleteVendor, arg.ID, arg.UserID)
	return err
}

const getVendorByID = `-- name: GetVendorByID :one
SELECT id, name, description, user_id, created_at, updated_at FROM vendors
WHERE id = $1
`

func (q *Queries) GetVendorByID(ctx context.Context, id pgtype.UUID) (Vendor, error) {
	row := q.db.QueryRow(ctx, getVendorByID, id)
	var i Vendor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVendorsByUserID = `-- name: ListVendorsByUserID :many
SELECT id, name, description, user_id, created_at, updated_at FROM vendors
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListVendorsByUserID(ctx context.Context, userID pgtype.UUID) ([]Vendor, error) {
	rows, err := q.db.Query(ctx, listVendorsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vendor{}
	for rows.Next() {
		var i Vendor
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVendor = `-- name: UpdateVendor :one
UPDATE vendors
SET
    name = COALESCE($3, name),
    description = COALESCE($4, description),
    updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, name, description, user_id, created_at, updated_at
`

type UpdateVendorParams struct {
	ID          pgtype.UUID `json:"id"`
	UserID      pgtype.UUID `json:"user_id"`
	Name        pgtype.Text `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpdateVendor(ctx context.Context, arg UpdateVendorParams) (Vendor, error) {
	row := q.db.QueryRow(ctx, updateVendor,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Description,
	)
	var i Vendor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
